name: lpath
channels:
    - conda-forge
    - defaults
dependencies:
    - python<3.12
    - westpa>=2022.03
    - scikit-learn
    - matplotlib
    - tqdm
    - networkx
    - pip
    - pip:
        - pylcs
        - ray
        - timedinput
        - .
